// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzwacdmvjzumxdsjaerf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6d2FjZG12anp1bXhkc2phZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTY4NDgsImV4cCI6MjA2MzkzMjg0OH0.vodDoW14knMcE0DcpF-VR0WH7G_ZRjiignefEHxbiug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);